{
  "robot": {
    "robot_type": "realman",
    "ip": null,
    "initial_joints_rad": [
      2.65586749,
      -0.06628761,
      -0.14056882,
      -1.26216978,
      0.11116002,
      -1.11919238,
      -0.45881216
    ]
  },
  "teleop": {
    "rotation_composition": "right",
    "vr_to_robot_axes": [
      [0.0, 0.0, 1.0],
      [-1.0, 0.0, 0.0],
      [0.0, 1.0, 0.0]
    ]
  }
}
